# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'words_search.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import typing

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget


class Ui_Words_Search_Form(object):

    def setupUi(self, Words_Search_Form):

        self.grid_n_rows  = 15
        self.grid_n_columns = 15

        Words_Search_Form.setObjectName("Words_Search_Form")
        Words_Search_Form.resize(600, 800)

        self.gridLayoutWidget = QtWidgets.QWidget(Words_Search_Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(350, 330, 152, 48))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 1, 1, 1)

        # for r in range(self.grid_n_columns):
        #     for c in range(self.grid_n_columns):
        #         button = QtWidgets.QPushButton(self.gridLayoutWidget)
        #         button.setMinimumSize(15,15)
        #         #button.setSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        #         self.gridLayout.addWidget(button,r,c,1,1)


        self.widget = QtWidgets.QWidget(Words_Search_Form)
        self.widget.setGeometry(QtCore.QRect(20, 490, 759, 65))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.remaining_time_label = QtWidgets.QLabel(self.widget)
        self.remaining_time_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.remaining_time_label.setObjectName("remaining_time_label")
        self.horizontalLayout_2.addWidget(self.remaining_time_label)
        self.found_words_label = QtWidgets.QLabel(self.widget)
        self.found_words_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.found_words_label.setObjectName("found_words_label")
        self.horizontalLayout_2.addWidget(self.found_words_label)
        self.words_to_find_label = QtWidgets.QLabel(self.widget)
        self.words_to_find_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.words_to_find_label.setObjectName("words_to_find_label")
        self.horizontalLayout_2.addWidget(self.words_to_find_label)
        self.widget1 = QtWidgets.QWidget(Words_Search_Form)
        self.widget1.setGeometry(QtCore.QRect(20, 580, 759, 129))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.start_pause_pushButton = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_pause_pushButton.sizePolicy().hasHeightForWidth())
        self.start_pause_pushButton.setSizePolicy(sizePolicy)
        self.start_pause_pushButton.setMaximumSize(QtCore.QSize(200, 50))
        self.start_pause_pushButton.setObjectName("start_pause_pushButton")
        self.horizontalLayout_4.addWidget(self.start_pause_pushButton)
        self.reset_game_pushButton = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_game_pushButton.sizePolicy().hasHeightForWidth())
        self.reset_game_pushButton.setSizePolicy(sizePolicy)
        self.reset_game_pushButton.setMaximumSize(QtCore.QSize(200, 50))
        self.reset_game_pushButton.setObjectName("reset_game_pushButton")
        self.horizontalLayout_4.addWidget(self.reset_game_pushButton)

        self.retranslateUi(Words_Search_Form)
        QtCore.QMetaObject.connectSlotsByName(Words_Search_Form)

    def retranslateUi(self, Words_Search_Form):
        _translate = QtCore.QCoreApplication.translate
        Words_Search_Form.setWindowTitle(_translate("Words_Search_Form", "Words Search"))
        self.remaining_time_label.setText(_translate("Words_Search_Form", "TextLabel"))
        self.found_words_label.setText(_translate("Words_Search_Form", "TextLabel"))
        self.words_to_find_label.setText(_translate("Words_Search_Form", "TextLabel"))
        self.start_pause_pushButton.setText(_translate("Words_Search_Form", "PushButton"))
        self.reset_game_pushButton.setText(_translate("Words_Search_Form", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Words_Search_Form = QtWidgets.QWidget()
    ui = Ui_Words_Search_Form()
    ui.setupUi(Words_Search_Form)
    Words_Search_Form.show()
    sys.exit(app.exec_())
