# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'words_search.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import typing

from PyQt5 import QtWidgets, QtCore
from PyQt5.QtCore import Qt, QSize

from utils.ui.ui_components import Buttons2DArrayWidget


class Ui_Words_Search_Form(object):

    def setupUi(self, Words_Search_Form, n_rows, n_columns):

        self.grid_n_rows  = n_rows
        self.grid_n_columns = n_columns

        Words_Search_Form.setObjectName("Words_Search_Form")
        Words_Search_Form.resize(600, 800)

        self.vertical_layout = QtWidgets.QVBoxLayout(Words_Search_Form)
        self.vertical_layout.setContentsMargins(10, 25, 10, 10)
        self.vertical_layout.setSpacing(0)
        self.horizontal_layout_1 = QtWidgets.QHBoxLayout(Words_Search_Form)
        self.horizontal_layout_1.setContentsMargins(0, 0, 0, 0)
        self.horizontal_layout_1.setSpacing(0)
        self.horizontal_layout_0 = QtWidgets.QHBoxLayout(Words_Search_Form)
        self.horizontal_layout_0.setContentsMargins(0, 0, 0, 0)
        self.horizontal_layout_0.setSpacing(0)

        self.buttons_array = Buttons2DArrayWidget(Words_Search_Form)
        self.buttons_array.setMaximumSize(500,500)
        self.vertical_layout.addWidget(self.buttons_array, 0, Qt.AlignCenter)

        self.vertical_layout.addLayout(self.horizontal_layout_1, 0)
        self.vertical_layout.addLayout(self.horizontal_layout_0, 0)

        self.remaining_time_label = QtWidgets.QLabel(Words_Search_Form)
        self.remaining_time_label.setAlignment(Qt.AlignCenter)
        self.remaining_time_label.setMaximumSize(100, 20)
        self.remaining_time_label.setMinimumSize(100, 20)
        self.remaining_time_label.setObjectName("remaining_time_label")
        self.remaining_time_label.setText('Remaining time: ')
        self.horizontal_layout_1.addWidget(self.remaining_time_label, 0, Qt.AlignCenter)
        self.found_words_label = QtWidgets.QLabel(Words_Search_Form)
        self.found_words_label.setAlignment(Qt.AlignCenter)
        self.found_words_label.setMaximumSize(100, 20)
        self.found_words_label.setMinimumSize(100, 20)
        self.found_words_label.setObjectName("found_words_label")
        self.found_words_label.setText('Found words: ')
        self.horizontal_layout_1.addWidget(self.found_words_label, 0, Qt.AlignCenter)
        self.words_to_find_label = QtWidgets.QLabel(Words_Search_Form)
        self.words_to_find_label.setAlignment(Qt.AlignCenter)
        self.words_to_find_label.setMaximumSize(100, 20)
        self.words_to_find_label.setMinimumSize(100, 20)
        self.words_to_find_label.setObjectName("words_to_find_label")
        self.words_to_find_label.setText('Words to find: ')
        self.horizontal_layout_1.addWidget(self.words_to_find_label, 0, Qt.AlignCenter)

        self.start_pause_pushButton = QtWidgets.QPushButton(Words_Search_Form)
        self.start_pause_pushButton.setMaximumSize(200, 75)
        self.start_pause_pushButton.setMinimumSize(200, 75)
        self.start_pause_pushButton.setObjectName("start_pause_pushButton")
        self.start_pause_pushButton.setText('Start')
        self.horizontal_layout_0.addWidget(self.start_pause_pushButton, 0, Qt.AlignCenter)

        self.reset_game_pushButton = QtWidgets.QPushButton(Words_Search_Form)
        self.reset_game_pushButton.setMaximumSize(200, 75)
        self.reset_game_pushButton.setMinimumSize(200, 75)
        self.reset_game_pushButton.setObjectName("reset_game_pushButton")
        self.reset_game_pushButton.setText('Reset')
        self.horizontal_layout_0.addWidget(self.reset_game_pushButton, 0, Qt.AlignCenter)

        Words_Search_Form.setLayout(self.vertical_layout)

        self.retranslateUi(Words_Search_Form)
        QtCore.QMetaObject.connectSlotsByName(Words_Search_Form)

    def retranslateUi(self, Words_Search_Form):
        _translate = QtCore.QCoreApplication.translate
        Words_Search_Form.setWindowTitle(_translate("Words_Search_Form", "Words Search"))
        self.remaining_time_label.setText(_translate("Words_Search_Form", "Remaining Time: "))
        self.found_words_label.setText(_translate("Words_Search_Form", "Words Found: "))
        self.words_to_find_label.setText(_translate("Words_Search_Form", "Words to Find: "))
        self.start_pause_pushButton.setText(_translate("Words_Search_Form", "Start"))
        self.reset_game_pushButton.setText(_translate("Words_Search_Form", "Reset"))


if __name__ == "__main__":
    import sys
    words_to_hide = ['BANANA', 'APPLE', 'STRAWBERRY', 'ORANGE', 'CHERRY']
    app = QtWidgets.QApplication(sys.argv)
    Words_Search_Form = QtWidgets.QWidget()
    ui = Ui_Words_Search_Form()
    ui.setupUi(Words_Search_Form, 15, 15)
    ui.buttons_array.hide_words(words_to_hide, mark_word=False)
    ui.buttons_array.random_populate_all_buttons(overwrite=False)
    Words_Search_Form.show()
    sys.exit(app.exec_())
