# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'words_matching.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(653, 506)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 631, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.WordsHintLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.WordsHintLineEdit.setFont(font)
        self.WordsHintLineEdit.setReadOnly(True)
        self.WordsHintLineEdit.setObjectName("WordsHintLineEdit")
        self.verticalLayout.addWidget(self.WordsHintLineEdit)
        self.wordDefinitionTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wordDefinitionTextEdit.setFont(font)
        self.wordDefinitionTextEdit.setReadOnly(True)
        self.wordDefinitionTextEdit.setObjectName("wordDefinitionTextEdit")
        self.verticalLayout.addWidget(self.wordDefinitionTextEdit)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeLeft_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeLeft_label.setFont(font)
        self.timeLeft_label.setObjectName("timeLeft_label")
        self.horizontalLayout.addWidget(self.timeLeft_label)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setMaximum(60)
        self.progressBar.setProperty("value", 60)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.resetPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetPushButton.sizePolicy().hasHeightForWidth())
        self.resetPushButton.setSizePolicy(sizePolicy)
        self.resetPushButton.setMinimumSize(QtCore.QSize(0, 100))
        self.resetPushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.resetPushButton.setObjectName("resetPushButton")
        self.horizontalLayout_2.addWidget(self.resetPushButton)
        self.startPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startPushButton.sizePolicy().hasHeightForWidth())
        self.startPushButton.setSizePolicy(sizePolicy)
        self.startPushButton.setMinimumSize(QtCore.QSize(0, 100))
        self.startPushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.startPushButton.setObjectName("startPushButton")
        self.horizontalLayout_2.addWidget(self.startPushButton)
        self.pausePushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pausePushButton.sizePolicy().hasHeightForWidth())
        self.pausePushButton.setSizePolicy(sizePolicy)
        self.pausePushButton.setMinimumSize(QtCore.QSize(0, 100))
        self.pausePushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pausePushButton.setObjectName("pausePushButton")
        self.horizontalLayout_2.addWidget(self.pausePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Words Matching!!!"))
        self.timeLeft_label.setText(_translate("Form", "Tiempo restante"))
        self.progressBar.setFormat(_translate("Form", "%v"))
        self.resetPushButton.setText(_translate("Form", "Reset"))
        self.startPushButton.setText(_translate("Form", "Start"))
        self.pausePushButton.setText(_translate("Form", "Pause"))

    def ui_init_status(self):
        self.startPushButton.setDisabled(False)
        self.resetPushButton.setDisabled(True)
        self.pausePushButton.setDisabled(True)
        self.lineEdit.setDisabled(True)
        self.startPushButton.setText('Start')
        self.lineEdit.clear()
        self.wordDefinitionTextEdit.clear()
        self.WordsHintLineEdit.clear()
        self.startPushButton.setFocus()
        self.lineEdit.setText("Put your answer here in format of Number:Word")

    def ui_running_status(self):
        self.startPushButton.setDisabled(True)
        self.resetPushButton.setDisabled(True)
        self.pausePushButton.setDisabled(False)
        self.lineEdit.setDisabled(False)
        self.startPushButton.setText('Start')
        self.WordsHintLineEdit.clear()
        self.lineEdit.clear()

    def ui_paused_status(self):
        self.startPushButton.setDisabled(False)
        self.resetPushButton.setDisabled(False)
        self.pausePushButton.setDisabled(True)
        self.lineEdit.setDisabled(True)
        self.startPushButton.setText('Resume')

    def ui_over_status(self):
        self.startPushButton.setDisabled(True)
        self.resetPushButton.setDisabled(True)
        self.pausePushButton.setDisabled(True)
        self.lineEdit.setDisabled(True)
        self.startPushButton.setText('Start')

    def ui_loading_data_status(self):
        self.startPushButton.setDisabled(True)
        self.resetPushButton.setDisabled(True)
        self.pausePushButton.setDisabled(True)
        self.lineEdit.setDisabled(True)
        self.startPushButton.setText('Loading Words...')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
