# -*- coding: utf-8 -*-
from PyQt5.QtGui import QFont
# Form implementation generated from reading ui file 'words_search.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QRadioButton, QSizePolicy, QLabel
from PyQt5 import QtWidgets, QtCore
from PyQt5.Qt import Qt
from utils.ui.ui_components import SudokuTableQWidget


class UiSudokuForm(object):
    width = 600
    heigth = 800

    def setupUi(self, SudokuForm):
        SudokuForm.setObjectName("SudokuForm")
        SudokuForm.resize(600, 800)

        self.vertical_layout = QtWidgets.QVBoxLayout(SudokuForm)
        self.vertical_layout.setContentsMargins(30, 30, 30, 30)
        self.vertical_layout.setSpacing(0)
        self.vertical_layout.setAlignment(Qt.AlignCenter)

        # status label
        self.status_label = QLabel(SudokuForm)
        self.status_label.setFont(QFont('Arial', 14))
        self.vertical_layout.addWidget(self.status_label, 0, Qt.AlignCenter)

        # create a table of 9x9
        self.sudoku_table = SudokuTableQWidget(SudokuForm)
        self.vertical_layout.addWidget(self.sudoku_table, 0, Qt.AlignCenter)

        # create and add the group of radio buttons
        self.groupBox = QtWidgets.QGroupBox(SudokuForm)
        self.groupBox.setMinimumSize(UiSudokuForm.width, 0)
        self.groupBox.setMaximumSize(UiSudokuForm.width, 100)
        self.groupBox.setSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("Difficulty Level")
        self.groupBox.setTitle('Difficulty Level')

        self.difficulty_h_layout = QtWidgets.QHBoxLayout(self.groupBox)
        self.difficulty_h_layout.setContentsMargins(0, 30, 0, 30)
        self.difficulty_h_layout.setSpacing(40)
        self.difficulty_h_layout.setAlignment(Qt.AlignCenter)

        self.n_levels_of_difficulty = 6
        for level_number in range(1, self.n_levels_of_difficulty):
            rb = QRadioButton('Level ' + str(level_number), self.groupBox)
            rb.setObjectName('level' + str(level_number))
            self.difficulty_h_layout.addWidget(rb)
        last_rb = QRadioButton('Solution', self.groupBox)
        last_rb.setObjectName('solution')
        self.difficulty_h_layout.addWidget(last_rb)
        self.groupBox.setLayout(self.difficulty_h_layout)
        self.difficulty_h_layout.itemAt(0).widget().click()

        self.vertical_layout.addWidget(self.groupBox, 0, Qt.AlignCenter)

        # create and add the buttons
        self.horizontal_layout_0 = QtWidgets.QHBoxLayout(None)
        self.horizontal_layout_0.setContentsMargins(0, 0, 0, 0)
        self.horizontal_layout_0.setSpacing(10)

        self.comprobar_solucion_pushButton = QtWidgets.QPushButton(SudokuForm)
        self.comprobar_solucion_pushButton.setMaximumSize(200, 75)
        self.comprobar_solucion_pushButton.setMinimumSize(200, 75)
        self.comprobar_solucion_pushButton.setObjectName("comprobar_solucion_pushButton")
        self.comprobar_solucion_pushButton.setText('Comprobar Solución')
        self.horizontal_layout_0.addWidget(self.comprobar_solucion_pushButton, 0, Qt.AlignCenter)
        self.vertical_layout.addLayout(self.horizontal_layout_0, 0)

        SudokuForm.setLayout(self.vertical_layout)
        self.retranslateUi(SudokuForm)

    def retranslateUi(self, Sudoku_Form):
        _translate = QtCore.QCoreApplication.translate
        Sudoku_Form.setWindowTitle(_translate("Sudoku_Form", "SUDOKU GAME"))
        self.comprobar_solucion_pushButton.setText(_translate("Sudoku_Form", "Comprobar Solución"))

    def ui_generating_sudoku_status(self):
        for n in range(0, self.n_levels_of_difficulty, 1):
            self.difficulty_h_layout.itemAt(n).widget().setDisabled(True)
        self.comprobar_solucion_pushButton.setDisabled(True)
        self.sudoku_table.setDisabled(True)
        self.status_label.setText('GENERATING SUDOKU....PLEASE WAIT!!!!')

    def ui_initiating_status(self):
        for n in range(0, self.n_levels_of_difficulty, 1):
            self.difficulty_h_layout.itemAt(n).widget().setDisabled(True)
        self.comprobar_solucion_pushButton.setDisabled(True)
        self.sudoku_table.setDisabled(True)
        self.status_label.setText('')

    def ui_running_status(self):
        for n in range(0, self.n_levels_of_difficulty, 1):
            self.difficulty_h_layout.itemAt(n).widget().setDisabled(False)
        self.comprobar_solucion_pushButton.setDisabled(False)
        self.sudoku_table.setDisabled(False)
        self.status_label.setText('*'*33 + '  ENJOY  ' + '*'*33)

    def ui_checking_solution_status(self):
        for n in range(0, self.n_levels_of_difficulty, 1):
            self.difficulty_h_layout.itemAt(n).widget().setDisabled(True)
        self.comprobar_solucion_pushButton.setDisabled(True)
        self.sudoku_table.setDisabled(True)
        self.status_label.setText('!!!!!CHECKING THE PROPOSED SOLUTION!!!!')

